# config file for automatic testing at travis-ci.org

language: python
# Ubuntu version
# dist: xenial

cache: pip

env:
    global:
        - LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
        #- SEGFAULT_SIGNALS=all

stages:
    - check
    - test
    # - doc

jobs:
    include:
        - stage: check
          python: 3.6
          env: TOXENV=check
          install: skip
          script: tox -v
        - stage: test
          python: 3.6
          env: TOXENV=py36
        - stage: test
          python: 3.7
          env: TOXENV=py37
        - stage: test
          python: 3.8
          env: TOXENV=py38
        - stage: test
          python: 3.9
          env: TOXENV=py39
        #- stage: doc
        #  python: 3.6
        #  script: travis-sphinx --nowarn --source=doc build


# command to install dependencies
install:
    - sudo apt-get update && sudo apt-get install -y graphviz
    - pip install -U pip setuptools
    - pip install .
    - pip install -r travis-requirements.txt

before_script:
    - python3 --version
    - ls -l /usr/bin/python{2,3}*
    - uname -a
    - lsb_release -a
    - virtualenv --version
    - easy_install --version
    - pip --version
    - pip install tox
    - tox --version
    - pip list

# command to run tests
script:
    - tox -v

#addons:
#    code_climate:
#        repo_token: $CODECLIMATE_REPO_TOKEN

after_failure:
  - more .tox/log/* | cat
  - more .tox/*/log/* | cat

# blacklist
branches:
    except:
        - gh-pages

notifications:
  email:
    on_success: never
    on_failure: always
